### ISSUE TITLE
Failing on webpack build

### ISSUE THREAD

**Issue by mfigurski80** [aaronpowell/webpack-golang-wasm-async-loader#14]
Getting the following error when I import my main.go file. Could this be a problem with my environment variables?

```
ERROR in ./src/main.go
Module build failed (from ./node_modules/golang-wasm-async-loader/dist/index.js):
Error: spawn undefined/bin/go ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:264:19)
    at onErrorNT (internal/child_process.js:456:16)
    at processTicksAndRejections (internal/process/task_queues.js:84:9)
 @ ./src/index.js 1:0-28 4:25-29
```

I do get the same error when cloning the repo and running the web example itself

**Comment by mfigurski80** [comment]
Note to anyone else encountering this issue: need to explicitly define variables `GOENV` and `GOROOT`. Does not take defaults. Does not take variables in `go env`
