### ISSUE TITLE
Error while running Example project

### ISSUE THREAD

**Issue by sudhanshu16** [aaronpowell/webpack-golang-wasm-async-loader#4]
Hey @aaronpowell!

First of all, thanks for the project!

I am trying to create a webapp that utilises WASM using GoLang. I followed the [example](https://github.com/aaronpowell/webpack-golang-wasm-async-loader/tree/master/example/web) provided by you but got the following errors in my browser's console: 
```
panic: syscall/js: Value.Call: property _makeFuncWrapper is not a function, got undefined
goroutine 1 [running]:
syscall/js.Value.Call(0x7ff8000000000006, 0x22255, 0x10, 0x4246d0, 0x1, 0x1, 0x40e050)
	/usr/local/opt/go/libexec/src/syscall/js/js.go:321 +0x86
syscall/js.FuncOf(0x40e050, 0x40e050, 0x12110001)
	/usr/local/opt/go/libexec/src/syscall/js/func.go:46 +0xa
github.com/aaronpowell/webpack-golang-wasm-async-loader/gobridge.RegisterCallback(0x2142b, 0x3, 0x25880)
	/Users/captain/go/src/github.com/aaronpowell/webpack-golang-wasm-async-loader/gobridge/gobridge.go:33 +0x3
main.main()
	/Users/captain/workspace/label-print/src/binaries/main.go:24 +0x3
```

My main.go looks like this: 
```
package main

import (
	"strconv"
	"syscall/js"

	"github.com/aaronpowell/webpack-golang-wasm-async-loader/gobridge"
)

func add(this js.Value, args []js.Value) (interface{}, error) {
	ret := 0

	for _, item := range args {
		val, _ := strconv.Atoi(item.String())
		ret += val
	}

	return ret, nil
}

func main() {
	c := make(chan struct{}, 0)

	gobridge.RegisterCallback("add", add)
	gobridge.RegisterValue("someValue", "Hello World")

	<-c
}
```

and my `App.js` looks like this: 

```
import React, { useEffect } from 'react';
import logo from './logo.svg';
import './App.css';
import wasm from './binaries/main.go';

const { add } = wasm;

function App() {
  const init = async () => {
    const res = await add(...[1, 2]);
    console.log(res)
  };
  useEffect(() => {
    init();
  }, []);
  return (
    <div className="App">
    </div>
  );
}

export default App;
```
Can you please tell me what is it that I am doing incorrectly?

**Comment by aaronpowell** [comment]
What version of Golang are you using?

**Comment by sudhanshu16** [comment]
@aaronpowell 

```
label-print git:(master)  go version
go version go1.13 darwin/amd64
```

**Comment by sudhanshu16** [comment]
Okay. So I downgraded Go to 1.12 and it works now.
Possibly it is because the `wasm_exec.js` that comes with this package is for Go 1.12 while I was using it with 1.13.

Maybe this package can somehow utilise the wasm_exec shipped with go cp `$(go env GOROOT)/misc/wasm/wasm_exec.js` or specify that a downgrade is needed.

Anyways this package is awesome. Really enjoying the dev env that comes with this ❤️

**Comment by sudhanshu16** [comment]
Raised a PR that references this issue. Closing this issue as it needs no further solving.
